# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]    

    operations = [

        migrations.AlterModelOptions(
            name='photoset',
            options={'ordering': ['date_update'], 'verbose_name': 'Photoset', 'verbose_name_plural': 'Photosets'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photoset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.Photoset'),
        ),

    ]


