# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 08:08
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161018_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='description',
            field=django_markdown.models.MarkdownField(default=b''),
        ),
    ]
